services:
  - type: web
    name: wonk-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /
    disk:
      name: wonk-data
      mountPath: /app/data
      sizeGB: 1
